### ISSUE TITLE
FIle name problem

### ISSUE THREAD

**Issue by tommy030314** [hwfan/DriveDownloader#9]
For example, if I download this file: https://sd74f-my.sharepoint.com/:u:/g/personal/akg1131_sd74f_onmicrosoft_com/EU_ZvUt21rdBlpjURjBBSHYBGHs5qTrkJJkGfXJOYDVDBw

the file saves 'PRETTY%C3%97CATION2 %E3%83%A9%E3%83%96%E3%83%A9%E3%83%96%E3%83%90%E3%83%BC%E3%82%B9%E3%83%87%E3%83%BC%E3%82%B3%E3%83%AC'
the original name is 'PRETTY×CATION2 ラブラブバースデーコレクション vol.4 －芦屋鈴鹿－'
I can't get original name by url decoder because the name is cutted on the middle
Is there a way to solve this?
Thanks

**Comment by hwfan** [comment]
Thanks for playing with DriveDownloader!
We've carefully checked your link, but it is inaccessible, which blocks me from reproducing the problem.
In my opinion, the main reason is that DriveDownloader can't deal with UTF-8 characters, since it's not tested in this case. I may use another link with such kind of characters and see what will happen.
